#Reproduce
minThreshold=0.2
maxThreshold=0.45
maxFitnessVariance=0.1
keepingPart=0.25
extremeTossing=false
#Species
speciesSizePenaltySteepness=2
averageNumberOfSpecies=10
#Delta
averageDeltaWeightConstant=1
excessNeuronsConstant=3.5
disjointNeuronsConstant=2.5
deltaThreshold=0.5
#Cycles
cycleDetectionNeuronThreshold=300
cycleDetectionLinkThreshold=1000
#Activation
forceHiddenActivationType=ReLU
forceOutputActivationType=None
#Mutation
scalingFactor=0.025
steepness=5
minFactor=0.0000000001
extremeMutationChance=0.01
amountOfMutationRolls=35
maxNeuronsPerMutation=1
maxEnabledLinksPerMutation=10
maxDisabledLinksPerMutation=10
weightMutationProb=0.5
biasMutationProb=0.3
addNeuronMutationProb=0.05
addLinkMutationProb=0.1
activationMutationProb=0.1